
 
cc_binary(
 
    name = "Cal",
    srcs = ["main.cpp"],
    deps = [
             ":calculator"
    ],
)
 
cc_library(
 
    name = "calculator",
    srcs= ["calculator.cpp"],
    hdrs = ["calculator.h"],
    visibility = ["//visibility:public"],
)

